AllCops:
  Exclude:
    - stribog.gemspec
    - Rakefile
    - bin/test.rb
    - lib/stribog/hash_params.rb
    - spec/**/*

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 13

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 120